trigger:
- master

strategy:
  matrix:

    'Build and Test on MacOS':
      purpose: 'library'
      imageName: 'macOS-latest'

    'Build and Test on Linux':
      purpose: 'library'
      imageName: 'ubuntu-latest'

    'Build and Test on Windows':
      purpose: 'library'
      imageName: 'windows-latest'

    'Rebuild Solution on Windows':
      purpose: 'solution'
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

### INSTALL NUGET AND RESTORE PACKAGES

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  condition: eq(variables['purpose'], 'library')
    
- task: NuGetCommand@2
  displayName: 'Restore packages'
  condition: eq(variables['purpose'], 'solution')
  inputs:
    restoreSolution: 'src/FftSharp.sln'

### BUILD THE CORE LIBRARY AND RUN TESTS

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: eq(variables['purpose'], 'library')
  inputs:
    command: 'build'
    projects: 'src/FftSharp/FftSharp.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  condition: eq(variables['purpose'], 'library')
  inputs:
    command: 'build'
    projects: 'src/FftSharp.Tests/FftSharp.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  condition: eq(variables['purpose'], 'library')
  inputs:
    command: test
    projects: 'src/FftSharp.Tests/FftSharp.Tests.csproj'

### REBUILD FULL SOLUTION
    
- task: VSBuild@1
  displayName: 'Build Release (Windows)'
  condition: eq(variables['purpose'], 'solution')
  inputs:
    solution: 'src/FftSharp.sln'
    configuration: 'release'