name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🦄 Use .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: ✨ NuGet Restore
        working-directory: src
        run: dotnet restore

      - name: 🛠️ Build Solution
        working-directory: src
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Run Tests
        working-directory: src
        run: dotnet test --no-restore
